"""empty message

Revision ID: 1124388b9a46
Revises: b03d7e297ee5
Create Date: 2023-06-29 07:41:28.202024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1124388b9a46'
down_revision = 'b03d7e297ee5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_type', sa.String(length=50)))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    op.drop_table('route_stage')
    # ### end Alembic commands ###