"""empty message

Revision ID: 1124388b9a46
Revises: b03d7e297ee5
Create Date: 2023-06-29 07:41:28.202024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1124388b9a46'
down_revision = 'b03d7e297ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    op.drop_table('route_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stage',
    sa.Column('route_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='route_stage_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_no'], ['stage.stage_no'], name='route_stage_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('route',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_distane', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
