"""empty message

Revision ID: 61804e32bc6a
Revises: 8b8faf8469ff
Create Date: 2023-07-05 16:04:49.192801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61804e32bc6a'
down_revision = '8b8faf8469ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_type', sa.String(length=20)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_distane', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('route_stage',
    sa.Column('route_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='route_stage_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_no'], ['stage.stage_no'], name='route_stage_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stage',
    sa.Column('stage_no', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('stage_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stage_description', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('stage_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
