"""relationship stages

Revision ID: 6864c78a7764
Revises: 3473ba2b15b8
Create Date: 2023-06-02 14:35:09.528001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6864c78a7764'
down_revision = '3473ba2b15b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'route', ['route_id'], ['route_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
