"""empty message

Revision ID: b03d7e297ee5
Revises: 63ad1c55bab3
Create Date: 2023-06-14 21:14:28.130827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b03d7e297ee5'
down_revision = '63ad1c55bab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('card_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('payment_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
